//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLavado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaVehiculo
    {
        public MarcaVehiculo()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int id_codigoMarcaV { get; set; }
        public Nullable<short> codigo { get; set; }
        public Nullable<int> fabricante { get; set; }
        public Nullable<int> tipo { get; set; }
        public string nombre_marca { get; set; }
    
        public virtual Fabricante Fabricante1 { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
