//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLavado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaVehiculo
    {
        public int id_codigoMarcaV { get; set; }
        public Nullable<short> codigo { get; set; }
        public string tipo { get; set; }
        public string fabricante { get; set; }
    }
}
