//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLavado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioProducto
    {
        public ServicioProducto()
        {
            this.Servicios_Facturados_Detalle = new HashSet<Servicios_Facturados_Detalle>();
            this.Servicios_Facturados_Detalle1 = new HashSet<Servicios_Facturados_Detalle>();
        }
    
        public short codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<float> precio { get; set; }
        public Nullable<short> tipo { get; set; }
    
        public virtual ICollection<Servicios_Facturados_Detalle> Servicios_Facturados_Detalle { get; set; }
        public virtual ICollection<Servicios_Facturados_Detalle> Servicios_Facturados_Detalle1 { get; set; }
    }
}
