//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLavado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoVehiculo
    {
        public TipoVehiculo()
        {
            this.MarcaVehiculo = new HashSet<MarcaVehiculo>();
        }
    
        public int id_codigoTV { get; set; }
        public Nullable<short> codigo { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<MarcaVehiculo> MarcaVehiculo { get; set; }
    }
}
