//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLavado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int id_vehiculo { get; set; }
        public string placa { get; set; }
        public Nullable<byte> numeroPuertas { get; set; }
        public Nullable<byte> numeroRuedas { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> marca { get; set; }
    
        public virtual MarcaVehiculo MarcaVehiculo { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
