//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLavado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.Servicios_Facturados_Encabezado = new HashSet<Servicios_Facturados_Encabezado>();
            this.Cliente = new HashSet<Cliente>();
        }
    
        public string placa { get; set; }
        public Nullable<short> tipo { get; set; }
        public Nullable<short> marca { get; set; }
        public Nullable<byte> numeroPuertas { get; set; }
        public Nullable<byte> numeroRuedas { get; set; }
    
        public virtual MarcaVehiculo MarcaVehiculo { get; set; }
        public virtual ICollection<Servicios_Facturados_Encabezado> Servicios_Facturados_Encabezado { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
