//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLavado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public int idcanton { get; set; }
        public int cedula { get; set; }
        public int id_Distrito { get; set; }
        public short codigofabricante { get; set; }
        public short codigovehiculo { get; set; }
        public int idprovincia { get; set; }
        public short codigoservicio { get; set; }
        public short codigotipovehiculo { get; set; }
        public int idusuario { get; set; }
        public string placa { get; set; }
        public int idser_fac { get; set; }
        public int id_ser { get; set; }
        public int id_fac { get; set; }
        public int codcliente { get; set; }
        public string codvecliente { get; set; }
    }
}
